add Github Action about clang-tidy
It add the Github Action about clang-tidy
which take charge of static analysis about source code.

Also, it fix the issues which are detected by clang-tidy.

Signed-off-by: Hyungrok.Kim <hr97gdi@sk.com>

diff --git a/.github/workflows/pull_request.yaml b/.github/workflows/pull_request.yaml
--- a/.github/workflows/pull_request.yaml
+++ b/.github/workflows/pull_request.yaml
@@ -10,9 +10,37 @@ jobs:
       - name: Run checkpatch review
         uses: webispy/checkpatch-action@master
 
+  clang_tidy_review:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out the repo
+        uses: actions/checkout@v2
+        with:
+          submodules: true
+      - name: Run clang-tidy review
+        run: |
+          docker run -t --rm -v $PWD:$PWD -w $PWD nugulinux/devenv:bionic /bin/bash -c "run_codereview.sh nugu-linux externals"
+          if [ ! -f "report.json" ]; then
+              echo "code checker error"
+              exit 1
+          fi
+          count=$(cat report.json | jq '.count')
+          if [ "$count" -gt "0" ]; then
+              for ((i=0; i<$count; i++))
+              do
+                  file=$(cat report.json | jq -r '.issues['$i'].file')
+                  line=$(cat report.json | jq -r '.issues['$i'].line')
+                  message=$(cat report.json | jq -r '.issues['$i'].message')
+
+                  echo "::warning file=$file,line=$line::$message"
+              done
+              rm report.json
+              exit 1
+          fi
+
   build:
     runs-on: ubuntu-latest
-    needs: checkpatch_review
+    needs: [checkpatch_review, clang_tidy_review]
     strategy:
       fail-fast: true
       matrix:
